apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  replicas: {{ .Values.icapservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.icapservice.applabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.icapservice.applabel }}
    spec:
      containers:
        - name: mvp-icap-service
          image: {{ .Values.imagestore.icapservice.registry}}{{ .Values.imagestore.icapservice.repository }}:{{ .Values.imagestore.icapservice.tag }}
          ports:
            - containerPort: 1344
            - containerPort: 1345
          envFrom:
          - configMapRef:
              name: icap-service-config
          volumeMounts:
            - name: source-vol
              mountPath: {{ .Values.volumemountpath.source }}
            - name: target-vol
              mountPath: {{ .Values.volumemountpath.target }}
            - name: tls-config-vol
              mountPath: /usr/local/c-icap/cert
              readOnly: true
      volumes:
        - name: source-vol
          persistentVolumeClaim:
            claimName: glasswallsource-pvc
        - name: target-vol
          persistentVolumeClaim:
            claimName: glasswalltarget-pvc
        - name: tls-config-vol
          secret:
            secretName: icap-service-tls-config


