apiVersion: v1
kind: Service
metadata:
  name: icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.icapservice.applabel }}
  ports:
  - port: 1344
    name: openport
    targetPort: {{ .Values.icapservice.port }}
  - port: 1345
    name: tlsport
    targetPort: {{ .Values.icapservice.tlsport }}

