apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.policyupdateservice.name }}
spec:
  replicas: {{ .Values.policyupdateservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.policyupdateservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.policyupdateservice.name }}     
    spec:
      containers:     
      - name: policy-update-service
        image: {{ .Values.imagestore.policyupdate.repository }}:{{ .Values.imagestore.policyupdate.tag }}
        ports:
        - containerPort: {{ .Values.policyupdateservice.port }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LISTENING_PORT
          value: "{{ .Values.policyupdateservice.port }}"
        - name: CONFIGMAP_NAME
          value: {{ .Values.requestprocessingservice.configmapname }}
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: policyupdateservicesecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: policyupdateservicesecret
              key: password 