apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
  ports:
  - port: {{ .Values.rabbitmqService.port }}
  selector:
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}